# Generated by Django 5.0.2 on 2024-06-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbackhub", "0002_company_administrator"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[("new", "New"), ("read", "Read"), ("finished", "Finished")],
                default="new",
                max_length=20,
            ),
        ),
    ]
