# Generated by Django 5.0.2 on 2024-06-11 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbackhub", "0004_alter_feedback_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feedbackhub.category",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="feedbackhub.company",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
