# Generated by Django 5.0.2 on 2024-06-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbackhub", "0005_alter_feedback_category_alter_feedback_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
